version: '3.8'

services:
  proctoring-api:
    build:
      context: .
      dockerfile: Dockerfile  # Sesuaikan jika perlu
    ports:
      - "5000:5000"
    volumes:
      - ./database:/app/database
      - ./modules:/app/modules
      - ./recognition_scripts:/app/recognition_scripts
      - ./logs:/app/logs
      - ./model:/app/model
    environment:
      - ROOT_DATABASE_DIR=/app/database
      - DEEPF_DATABASE_DIR=processed_dataset
    restart: unless-stopped